# Site settings
url: http://www.ksol.fr
title: Kevin Soltysiak
email: kevin@ksol.fr
description: "I'm a freelance web developer"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/ksol
  - title: stack-overflow
    url: https://stackoverflow.com/users/669020/ksol
  - title: twitter
    url: https://twitter.com/ksol
  - title: linkedin
    url: https://linkedin.com/in/ksoltysiak
# Postal address (add as many lines as necessary)
address:
  - line: Strasbourg, France

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap
