# Site settings
title: Kevin Soltysiak
email: kevin@ksol.fr
description: "I'm a freelance web developper"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: E2ECF0 #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F
  blog-link: 567698
  blog-link-secondary: 80A4CA
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/ksol
  - title: stack-overflow
    url: https://stackoverflow.com/users/669020/ksol
  - title: linkedin
    url: https://www.linkedin.com/in/ksoltysiak
  - title: bitbucket
    url: https://bitbucket.org/ksol
  - title: github
    url: https://github.com/ksol

# Postal address (add as many lines as necessary)
address:
  - line: Strasbourg, France

# Build settings
markdown: kramdown
